//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perf.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Perf.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food &amp; Entertainment
        ///Rental
        ///Transportation
        ///Visitor Service
        ///Accommodation
        ///Natural Attraction
        ///Tourism Marketing Partner
        ///Guided Tour.
        /// </summary>
        internal static string Wordlist_Categories {
            get {
                return ResourceManager.GetString("Wordlist_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aol.com
        ///fastmail.com
        ///gmail.com
        ///gmx.com
        ///icloud.com
        ///yahoo.com
        ///hotmail.com
        ///mail.com
        ///yandex.com.
        /// </summary>
        internal static string Wordlist_Domains {
            get {
                return ResourceManager.GetString("Wordlist_Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith
        ///Johnson
        ///Williams
        ///Brown
        ///Jones
        ///Garcia
        ///Rodriguez
        ///Miller
        ///Martinez
        ///Davis
        ///Hernandez
        ///Lopez
        ///Gonzalez
        ///Wilson
        ///Anderson
        ///Thomas
        ///Taylor
        ///Lee
        ///Moore
        ///Jackson
        ///Perez
        ///Martin
        ///Thompson
        ///White
        ///Sanchez
        ///Harris
        ///Ramirez
        ///Clark
        ///Lewis
        ///Robinson
        ///Walker
        ///Young
        ///Hall
        ///Allen
        ///Torres
        ///Nguyen
        ///Wright
        ///Flores
        ///King
        ///Scott
        ///Rivera
        ///Green
        ///Hill
        ///Adams
        ///Baker
        ///Nelson
        ///Mitchell
        ///Campbell
        ///Gomez
        ///Carter
        ///Roberts
        ///Diaz
        ///Phillips
        ///Evans
        ///Turner
        ///Reyes
        ///Cruz
        ///Parker
        ///Edwards
        ///Collins
        ///Stewart
        ///Morris
        ///Morales
        ///Ortiz
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wordlist_Names {
            get {
                return ResourceManager.GetString("Wordlist_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///of
        ///to
        ///and
        ///a
        ///in
        ///is
        ///it
        ///you
        ///that
        ///he
        ///was
        ///for
        ///on
        ///are
        ///with
        ///as
        ///I
        ///his
        ///they
        ///be
        ///at
        ///one
        ///have
        ///this
        ///from
        ///or
        ///had
        ///by
        ///hot
        ///word
        ///but
        ///what
        ///some
        ///we
        ///can
        ///out
        ///other
        ///were
        ///all
        ///there
        ///when
        ///up
        ///use
        ///your
        ///how
        ///said
        ///an
        ///each
        ///she
        ///which
        ///do
        ///their
        ///time
        ///if
        ///will
        ///way
        ///about
        ///many
        ///then
        ///them
        ///write
        ///would
        ///like
        ///so
        ///these
        ///her
        ///long
        ///make
        ///thing
        ///see
        ///him
        ///two
        ///has
        ///look
        ///more
        ///day
        ///could
        ///go
        ///come
        ///did
        ///number
        ///sound
        ///no
        ///most
        ///people
        ///my
        ///over
        ///know
        ///water
        ///than
        ///call
        ///first
        ///who
        ///may
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wordlist_Words {
            get {
                return ResourceManager.GetString("Wordlist_Words", resourceCulture);
            }
        }
    }
}
